services:
  - type: web
    name: cloud_exo
    env: node
    region: frankfurt
    buildCommand: npm install
    startCommand: yarn start
    branch: master
    plan: free
    envVars:
      DATABASE_URL: 
        fromDatabase: cloud_exo_db

databases:
  - name: cloud_exo_db
    region: frankfurt
    plan: free
    databaseName: cloud_exo_db
    user: admin
