services:
  - type: web
    name: cloud_exo
    env: node
    region: frankfurt
    buildCommand: npm install
    startCommand: yarn start
    branch: master
    plan: free
    envVars:
      DATABASE_URL:
        fromDatabase:
          name: cloud_exo_db
      API_SECRET:
        sync: false # Demande manuelle pour les secrets dans le tableau de bord Render
      NODE_ENV:
        value: production

databases:
  - name: cloud_exo_db
    region: frankfurt
    plan: free
    databaseName: cloud_exo_db
    user: admin

envVarGroups:
  - name: common-env
    envVars:
      - key: APP_PORT
        value: 3000
      - key: LOG_LEVEL
        value: info
