services:
  - type: web
    name: cloud_exo
    env: node
    region: frankfurt
    buildCommand: npm install
    startCommand: yarn start
    plan: free
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: cloud_exo
          property: connectionString

databases:
  - name: cloud_exo_db
    region: frankfurt
    plan: free
    databaseName: cloud_exo_db
    user: admin